name: claygo_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.1.1+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  cloud_firestore: ^4.15.8
  firebase_analytics: ^10.8.9
  firebase_core: ^2.27.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
