name: claygo_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.1.1+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  cloud_firestore: ^4.15.8
  firebase_analytics: ^10.8.9
  firebase_core: ^2.27.0
  toastification: ^1.2.1
  flutter:
    sdk: flutter
  intl: ^0.19.0
  flutter_local_notifications: ^17.0.0
  workmanager: ^0.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
