// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIQxmlwlBqubx-uVyaXRIkbr5U-W2h8J8',
    appId: '1:265643527010:web:497fcacd0b5ba84e28fa3b',
    messagingSenderId: '265643527010',
    projectId: 'claygo-app',
    authDomain: 'claygo-app.firebaseapp.com',
    storageBucket: 'claygo-app.appspot.com',
    measurementId: 'G-SR7PQGZZ4H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbgRAeMZaKcYEtFvr1R6adoS3x4kkY42E',
    appId: '1:265643527010:android:b3524ced5150617328fa3b',
    messagingSenderId: '265643527010',
    projectId: 'claygo-app',
    storageBucket: 'claygo-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXkdsn5PxkQvL3M61ksKi4_QrO8ucrmqk',
    appId: '1:265643527010:ios:e9b29b9891858b1128fa3b',
    messagingSenderId: '265643527010',
    projectId: 'claygo-app',
    storageBucket: 'claygo-app.appspot.com',
    iosBundleId: 'com.example.claygoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXkdsn5PxkQvL3M61ksKi4_QrO8ucrmqk',
    appId: '1:265643527010:ios:2cc5a971d2368d2728fa3b',
    messagingSenderId: '265643527010',
    projectId: 'claygo-app',
    storageBucket: 'claygo-app.appspot.com',
    iosBundleId: 'com.example.claygoApp.RunnerTests',
  );
}
